// Demo catalogue for the Mila-Karton launch build.
// Replace model, price, warranty, stock, and imagery with owner-approved data before launch.
const image = "/images/electronics-placeholder.svg";

const common = {
  image,
  availability: "In Stock",
  shipping: "Delivery calculated at checkout",
  returnPolicy:
    "Eligible returns within 3 days for damaged, defective, or incorrect items",
  delivery: "3-7 business days",
};

const demoproducts = [
  {
    id: 1,
    name: "Pulse Mini Bluetooth Speaker",
    brand: "Mila-Karton Select",
    category: "Audio",
    image: "/images/img1.avif",
    price: 4499,
    originalPrice: 5499,
    shortDescription:
      "Compact wireless speaker with room-filling sound for everyday listening.",
    description:
      "A small, portable speaker designed for desks, bedrooms, and weekend trips. The balanced sound profile and simple wireless pairing make it an easy everyday companion.",
    specifications: {
      connectivity: "Bluetooth 5.3",
      battery: "Up to 12 hours",
      charging: "USB-C",
      waterResistance: "Splash resistant",
    },
    rating: 4.6,
    reviews: 42,
    warranty: "1 Year Seller Warranty",
    stock: 35,
    createdAt: "2026-07-01",
  },
  {
    id: 2,
    name: "ClearCall Wireless Earbuds",
    brand: "Mila-Karton Select",
    category: "Audio",
    image: "/images/img2.avif",
    price: 6999,
    originalPrice: 7999,
    shortDescription:
      "Lightweight true-wireless earbuds with clear calls and a pocket charging case.",
    description:
      "Designed for workdays and commutes, these true-wireless earbuds combine a comfortable fit, touch controls, and dependable battery life in a compact case.",
    specifications: {
      connectivity: "Bluetooth 5.3",
      battery: "Up to 28 hours with case",
      microphone: "Dual-mic calls",
      charging: "USB-C",
    },
    rating: 4.5,
    reviews: 37,
    warranty: "1 Year Seller Warranty",
    stock: 48,
    createdAt: "2026-07-02",
  },
  {
    id: 3,
    name: "BassBox Portable Party Speaker",
    brand: "Mila-Karton Select",
    category: "Audio",
    image: "/images/img3.avif",
    price: 12499,
    originalPrice: 14999,
    shortDescription:
      "Portable high-output speaker with deep bass, lighting, and microphone input.",
    description:
      "Bring powerful sound to gatherings with a carry-friendly party speaker, wireless playback, microphone input, and a configurable ambient light ring.",
    specifications: {
      output: "60 W RMS",
      connectivity: "Bluetooth, AUX, USB",
      battery: "Up to 10 hours",
      controls: "Bass and treble",
    },
    rating: 4.7,
    reviews: 29,
    warranty: "1 Year Seller Warranty",
    stock: 21,
    createdAt: "2026-07-03",
  },
  {
    id: 4,
    name: "ArcView 2.1 Soundbar",
    brand: "Mila-Karton Select",
    category: "Audio",
    image: "/images/img4.avif",
    price: 18999,
    originalPrice: 22999,
    shortDescription:
      "Slim soundbar with wireless subwoofer support for a clean home setup.",
    description:
      "A minimalist television audio upgrade with dialogue-focused modes, wireless connectivity, and a low-profile design that sits neatly below a screen.",
    specifications: {
      channels: "2.1",
      connectivity: "HDMI ARC, Bluetooth, Optical",
      modes: "Movie, Music, Voice",
      output: "120 W",
    },
    rating: 4.6,
    reviews: 24,
    warranty: "1 Year Seller Warranty",
    stock: 16,
    createdAt: "2026-07-04",
  },
  {
    id: 5,
    name: "QuietFit ANC Headphones",
    brand: "Mila-Karton Select",
    category: "Audio",
    image: "/images/img5.avif",
    price: 14999,
    originalPrice: 17999,
    shortDescription:
      "Over-ear wireless headphones with adaptive noise cancellation and a fold-flat design.",
    description:
      "Comfortable over-ear headphones for travel, study, and focused work with adjustable noise control, a built-in microphone, and long listening sessions.",
    specifications: {
      connectivity: "Bluetooth 5.3",
      noiseControl: "Hybrid ANC",
      battery: "Up to 40 hours",
      charging: "USB-C fast charge",
    },
    rating: 4.7,
    reviews: 51,
    warranty: "1 Year Seller Warranty",
    stock: 19,
    createdAt: "2026-07-05",
  },
  {
    id: 6,
    name: "BeamLite 4K Smart Projector",
    brand: "Mila-Karton Select",
    image: "/images/img6.avif",
    category: "Home Entertainment",
    price: 29999,
    originalPrice: 34999,
    shortDescription:
      "Compact smart projector for cinema nights, presentations, and casual gaming.",
    description:
      "A flexible home projector with a crisp 4K-compatible picture, built-in streaming interface, automatic keystone correction, and easy wireless casting.",
    specifications: {
      resolution: "Full HD native, 4K compatible",
      brightness: "500 ANSI lumens",
      connectivity: "Wi-Fi, Bluetooth, HDMI",
      speaker: "Built-in 10 W",
    },
    rating: 4.4,
    reviews: 18,
    warranty: "1 Year Seller Warranty",
    stock: 12,
    createdAt: "2026-07-06",
  },
  {
    id: 7,
    name: "ViewPoint 27 Smart Monitor",
    brand: "Mila-Karton Select",
    image: "/images/img7.avif",
    category: "Computing",
    price: 24999,
    originalPrice: 28999,
    shortDescription:
      "27-inch edge-to-edge monitor for work, streaming, and creative setups.",
    description:
      "A clean desk monitor with a sharp display, wide viewing angles, built-in speakers, and multiple ports for a flexible home or office workstation.",
    specifications: {
      display: "27-inch QHD",
      refreshRate: "100 Hz",
      ports: "HDMI, DisplayPort, USB-C",
      features: "Built-in speakers, low blue light",
    },
    rating: 4.5,
    reviews: 33,
    warranty: "1 Year Seller Warranty",
    stock: 14,
    createdAt: "2026-07-07",
  },
  {
    id: 8,
    name: "CoreType Mechanical Desk Set",
    brand: "Mila-Karton Select",
    image: "/images/img8.avif",
    category: "Computing",
    price: 8499,
    originalPrice: 9999,
    shortDescription:
      "Compact mechanical keyboard and precision wireless mouse for a minimal desk.",
    description:
      "A practical keyboard-and-mouse set for people who want a cleaner, more responsive workspace without adding unnecessary bulk.",
    specifications: {
      keyboard: "Hot-swappable mechanical keys",
      mouse: "Adjustable DPI",
      connectivity: "2.4 GHz wireless",
      battery: "Rechargeable",
    },
    rating: 4.6,
    reviews: 27,
    warranty: "1 Year Seller Warranty",
    stock: 31,
    createdAt: "2026-07-08",
  },
  {
    id: 9,
    name: "MeshLink Wi-Fi 6 Router",
    brand: "Mila-Karton Select",
    image: "/images/img9.avif",
    category: "Networking",
    price: 11999,
    originalPrice: 13999,
    shortDescription:
      "Fast dual-band router for connected homes, streaming, and smart devices.",
    description:
      "A reliable Wi-Fi 6 router with app-based setup, guest networking, parental controls, and enough capacity for a busy connected home.",
    specifications: {
      wireless: "Wi-Fi 6 AX3000",
      coverage: "Up to 2,000 sq ft",
      ports: "1 WAN, 4 LAN",
      security: "WPA3",
    },
    rating: 4.5,
    reviews: 22,
    warranty: "1 Year Seller Warranty",
    stock: 26,
    createdAt: "2026-07-09",
  },
  {
    id: 10,
    name: "OfficeJet Mono Laser Printer",
    brand: "Mila-Karton Business",
    image: "/images/img10.avif",
    category: "Printers",
    price: 17999,
    originalPrice: 20999,
    shortDescription:
      "Efficient monochrome laser printer for home offices and small teams.",
    description:
      "A dependable black-and-white printer for everyday documents, with automatic duplex printing, wireless setup, and a compact footprint.",
    specifications: {
      printSpeed: "Up to 28 ppm",
      paperSize: "A4",
      duplex: "Automatic",
      connectivity: "Wi-Fi, USB",
    },
    rating: 4.5,
    reviews: 16,
    warranty: "1 Year Manufacturer Warranty",
    stock: 10,
    createdAt: "2026-07-10",
  },
  {
    id: 11,
    name: "ColourTank A4 Ink Printer",
    brand: "Mila-Karton Business",
    image: "/images/img11.avif",
    category: "Printers",
    price: 24999,
    originalPrice: 28999,
    shortDescription:
      "Low-cost colour ink-tank printer for documents, projects, and everyday photos.",
    description:
      "A practical colour printer with refillable tanks, wireless printing, scanning, and copying for homes, students, and small businesses.",
    specifications: {
      functions: "Print, scan, copy",
      paperSize: "A4",
      connectivity: "Wi-Fi, USB",
      duplex: "Manual",
    },
    rating: 4.4,
    reviews: 19,
    warranty: "1 Year Manufacturer Warranty",
    stock: 11,
    createdAt: "2026-07-11",
  },
  {
    id: 12,
    name: "ProPrint A3 Colour Laser",
    brand: "Mila-Karton Business",
    image: "/images/img12.avif",
    category: "Printers",
    price: 74999,
    originalPrice: 84999,
    shortDescription:
      "A3 colour laser printer for marketing materials, reports, and professional documents.",
    description:
      "A high-capacity colour printer concept for growing offices that need consistent output, flexible paper handling, and network-ready printing.",
    specifications: {
      printSpeed: "Up to 25 ppm",
      paperSize: "A3 and A4",
      connectivity: "Ethernet, Wi-Fi, USB",
      features: "Duplex and network printing",
    },
    rating: 4.5,
    reviews: 8,
    warranty: "1 Year Manufacturer Warranty",
    stock: 5,
    createdAt: "2026-07-12",
  },
  {
    id: 13,
    name: "WorkCentre Duplex Office Printer",
    brand: "Mila-Karton Business",
    image: "/images/img13.avif",
    category: "Printers",
    price: 119999,
    originalPrice: 134999,
    shortDescription:
      "High-volume multifunction printer for teams that need speed and reliable workflows.",
    description:
      "A professional office printer concept with fast duplex workflows, secure print options, scanning, and broad network administration support.",
    specifications: {
      functions: "Print, scan, copy",
      printSpeed: "Up to 40 ppm",
      paperSize: "A4",
      connectivity: "Gigabit Ethernet, Wi-Fi",
    },
    rating: 4.6,
    reviews: 6,
    warranty: "1 Year Manufacturer Warranty",
    stock: 3,
    createdAt: "2026-07-13",
  },
  {
    id: 14,
    name: "PocketPrint Photo Printer",
    brand: "Mila-Karton Select",
    image: "/images/img14.avif",
    category: "Printers",
    price: 9499,
    originalPrice: 10999,
    shortDescription:
      "Pocket-sized wireless photo printer for instant keepsakes and labels.",
    description:
      "A compact photo printer that turns phone images into small keepsakes through a simple companion app and wireless connection.",
    specifications: {
      printSize: "2 x 3 inch",
      connectivity: "Bluetooth",
      power: "Rechargeable battery",
      app: "Android and iOS",
    },
    rating: 4.3,
    reviews: 14,
    warranty: "6 Months Seller Warranty",
    stock: 22,
    createdAt: "2026-07-14",
  },
  {
    id: 15,
    name: "FrameOne Creator Camera",
    brand: "Mila-Karton Studio",
    image: "/images/img15.avif",
    category: "Cameras",
    price: 54999,
    originalPrice: 62999,
    shortDescription:
      "Flexible camera body for content creators, travel, and first studio setups.",
    description:
      "A creator-focused camera concept with interchangeable lens support, fast autofocus, and a flip display for video and still photography.",
    specifications: {
      sensor: "APS-C",
      video: "4K recording",
      display: "Vari-angle touchscreen",
      connectivity: "Wi-Fi and Bluetooth",
    },
    rating: 4.6,
    reviews: 11,
    warranty: "1 Year Manufacturer Warranty",
    stock: 6,
    createdAt: "2026-07-15",
  },
  {
    id: 16,
    name: "LumaMirrorless Creator Kit",
    brand: "Mila-Karton Studio",
    image: "/images/img16.avif",
    category: "Cameras",
    price: 89999,
    originalPrice: 99999,
    shortDescription:
      "Mirrorless camera kit with lens, clean 4K video, and creator-friendly controls.",
    description:
      "A versatile mirrorless kit for product shoots, travel content, and small business campaigns, packaged with an everyday zoom lens.",
    specifications: {
      sensor: "Full-frame",
      video: "4K 60 fps",
      stabilization: "In-body stabilization",
      kit: "Camera body plus 24-70 mm lens",
    },
    rating: 4.7,
    reviews: 9,
    warranty: "1 Year Manufacturer Warranty",
    stock: 4,
    createdAt: "2026-07-16",
  },
  {
    id: 17,
    name: "ActionCam 4K Adventure Kit",
    brand: "Mila-Karton Studio",
    image: "/images/img17.avif",  
    category: "Cameras",
    price: 39999,
    originalPrice: 44999,
    shortDescription:
      "Rugged 4K action camera with stabilization and a ready-to-shoot accessory kit.",
    description:
      "A small adventure camera for travel, cycling, and behind-the-scenes content with a protective case and useful mounting accessories.",
    specifications: {
      video: "4K 60 fps",
      stabilization: "Electronic stabilization",
      waterResistance: "Up to 10 m with case",
      display: "Dual colour screens",
    },
    rating: 4.5,
    reviews: 17,
    warranty: "1 Year Manufacturer Warranty",
    stock: 8,
    createdAt: "2026-07-17",
  },
  {
    id: 18,
    name: "SoftBox LED Studio Pair",
    brand: "Mila-Karton Studio",
    image: "/images/img18.avif",
    category: "Studio Equipment",
    price: 34999,
    originalPrice: 39999,
    shortDescription:
      "Two-panel LED lighting set for portraits, product shoots, and video calls.",
    description:
      "A practical two-light kit with adjustable brightness, soft diffusion, and stands for simple home studio or product photography setups.",
    specifications: {
      lights: "2 LED panels",
      colourTemperature: "3200-5600 K",
      control: "On-panel controls",
      kit: "Stands and diffusers included",
    },
    rating: 4.6,
    reviews: 13,
    warranty: "1 Year Seller Warranty",
    stock: 9,
    createdAt: "2026-07-18",
  },
  {
    id: 19,
    name: "BrightBeam COB Video Light",
    brand: "Mila-Karton Studio",
    image: "/images/img19.avif",
    category: "Studio Equipment",
    price: 49999,
    originalPrice: 57999,
    shortDescription:
      "High-output bi-colour COB light for controlled studio and location work.",
    description:
      "A powerful creator light with adjustable colour temperature, quiet cooling, and a standard modifier mount for polished product and portrait work.",
    specifications: {
      output: "150 W",
      colourTemperature: "2700-6500 K",
      control: "App and on-body",
      mount: "Bowens compatible",
    },
    rating: 4.7,
    reviews: 7,
    warranty: "1 Year Seller Warranty",
    stock: 5,
    createdAt: "2026-07-19",
  },
  {
    id: 20,
    name: "ClearVoice Wireless Mic Kit",
    brand: "Mila-Karton Studio",
    image: "/images/img20.avif",
    category: "Studio Equipment",
    price: 19999,
    originalPrice: 23999,
    shortDescription:
      "Dual wireless microphone kit for interviews, reels, and classroom content.",
    description:
      "A simple two-transmitter wireless kit with noise reduction, a compact receiver, and charging case for mobile and camera workflows.",
    specifications: {
      transmitters: "2",
      range: "Up to 100 m line of sight",
      battery: "Up to 8 hours",
      compatibility: "USB-C and camera output",
    },
    rating: 4.5,
    reviews: 21,
    warranty: "1 Year Seller Warranty",
    stock: 13,
    createdAt: "2026-07-20",
  },
  {
    id: 21,
    name: "StudioTrack 4K PTZ Camera",
    brand: "Mila-Karton Studio",
    image: "/images/img21.avif",
    category: "Studio Equipment",
    price: 149999,
    originalPrice: 169999,
    shortDescription:
      "Remote-controlled 4K PTZ camera for classrooms, events, and studio streaming.",
    description:
      "A professional camera concept with smooth pan, tilt, and zoom control for streaming spaces, meeting rooms, and compact production studios.",
    specifications: {
      video: "4K output",
      zoom: "12x optical",
      control: "Remote PTZ and presets",
      outputs: "HDMI, USB, network",
    },
    rating: 4.7,
    reviews: 4,
    warranty: "1 Year Manufacturer Warranty",
    stock: 2,
    createdAt: "2026-07-21",
  },
  {
    id: 22,
    name: "PowerNest Home UPS",
    brand: "Mila-Karton Power",
    image: "/images/img22.avif",  
    category: "Power & Backup",
    price: 34999,
    originalPrice: 39999,
    shortDescription:
      "Compact backup power system for routers, workstations, and essential devices.",
    description:
      "A clean, quiet backup system for home offices and small studios with multiple outputs and a clear battery-status display.",
    specifications: {
      capacity: "1200 VA",
      outputs: "AC, USB-A, USB-C",
      display: "LCD status panel",
      protection: "Surge and overload protection",
    },
    rating: 4.4,
    reviews: 12,
    warranty: "1 Year Seller Warranty",
    stock: 7,
    createdAt: "2026-07-22",
  },
  {
    id: 23,
    name: "VaultStore Four-Bay NAS",
    brand: "Mila-Karton Pro",
    image: "/images/img23.avif",
    category: "Computing",
    price: 79999,
    originalPrice: 89999,
    shortDescription:
      "Four-bay network storage for creators, teams, and secure home backups.",
    description:
      "A flexible storage hub for centralised file access, automated backups, media libraries, and small-team collaboration.",
    specifications: {
      bays: "4 drive bays",
      networking: "2.5 GbE",
      features: "Snapshots and remote access",
      drives: "Drive-free enclosure",
    },
    rating: 4.6,
    reviews: 5,
    warranty: "2 Year Seller Warranty",
    stock: 3,
    createdAt: "2026-07-23",
  },
  {
    id: 24,
    name: "CreatorCore Performance Laptop",
    brand: "Mila-Karton Pro",
    image: "/images/img24.avif",
    category: "Computing",
    price: 149999,
    originalPrice: 169999,
    shortDescription:
      "High-performance laptop for editing, design, code, and demanding everyday work.",
    description:
      "A premium workstation-style laptop concept with a colour-accurate screen, fast storage, and enough headroom for creative and professional workloads.",
    specifications: {
      display: "16-inch QHD",
      memory: "32 GB",
      storage: "1 TB SSD",
      graphics: "Dedicated graphics",
    },
    rating: 4.7,
    reviews: 8,
    warranty: "1 Year Manufacturer Warranty",
    stock: 4,
    createdAt: "2026-07-24",
  },
  {
    id: 25,
    name: "StudioPanel OLED Monitor",
    brand: "Mila-Karton Pro",
    image: "/images/img25.avif",
    category: "Computing",
    price: 174999,
    originalPrice: 194999,
    shortDescription:
      "Premium OLED monitor for colour-critical creative and production work.",
    description:
      "A high-end display concept for editors, designers, and studios seeking deep contrast, smooth motion, and a refined minimalist desk presence.",
    specifications: {
      display: "32-inch 4K OLED",
      refreshRate: "120 Hz",
      colour: "Wide-gamut coverage",
      connectivity: "HDMI 2.1, DisplayPort, USB-C",
    },
    rating: 4.8,
    reviews: 3,
    warranty: "2 Year Manufacturer Warranty",
    stock: 2,
    createdAt: "2026-07-25",
  },
  {
    id: 26,
    name: "VoltGo Portable Power Station Pro",
    brand: "Mila-Karton Power",
    image: "/images/img26.avif",
    category: "Power & Backup",
    price: 199999,
    originalPrice: 224999,
    shortDescription:
      "Large-capacity portable power station for work, travel, and emergency backup.",
    description:
      "A high-capacity power unit concept with multiple charging options for mobile workstations, events, outdoor production, and home backup.",
    specifications: {
      capacity: "2048 Wh",
      output: "2400 W continuous",
      charging: "AC, solar, car",
      outputs: "AC, USB-C PD, 12 V",
    },
    rating: 4.6,
    reviews: 4,
    warranty: "2 Year Seller Warranty",
    stock: 2,
    createdAt: "2026-07-26",
  },
  {
    id: 27,
    name: "UrbanGlide Electric Cycle",
    brand: "Mila-Karton Mobility",
    image: "/images/img27.avif",
    category: "Electric Mobility",
    price: 199999,
    originalPrice: 219999,
    shortDescription:
      "Comfort-first electric cycle for city commutes and relaxed weekend rides.",
    description:
      "A practical urban electric cycle concept with a comfortable riding position, integrated lighting, and assistance designed for everyday city travel.",
    specifications: {
      motor: "250 W hub motor",
      battery: "36 V removable battery",
      range: "Up to 70 km claimed range",
      frame: "Aluminium alloy",
    },
    rating: 4.5,
    reviews: 6,
    warranty: "1 Year Manufacturer Warranty",
    stock: 3,
    createdAt: "2026-07-27",
  },
  {
    id: 28,
    name: "TrailVolt Touring Electric Cycle",
    brand: "Mila-Karton Mobility",
    image: "/images/img28.avif",
    category: "Electric Mobility",
    price: 249999,
    originalPrice: 279999,
    shortDescription:
      "Long-range electric cycle concept for touring, trails, and comfortable exploration.",
    description:
      "A premium touring electric cycle concept with a larger battery, suspension comfort, and practical carrying mounts for longer rides.",
    specifications: {
      motor: "500 W mid-drive",
      battery: "48 V high-capacity battery",
      range: "Up to 110 km claimed range",
      features: "Hydraulic brakes and front suspension",
    },
    rating: 4.7,
    reviews: 3,
    warranty: "2 Year Manufacturer Warranty",
    stock: 1,
    createdAt: "2026-07-28",
  },
  {
    id: 29,
    name: "ProGlow Three-Light Studio Kit",
    brand: "Mila-Karton Studio",
    image: "/images/img29.avif",  
    category: "Studio Equipment",
    price: 174999,
    originalPrice: 194999,
    shortDescription:
      "Complete three-light setup for professional product, portrait, and video production.",
    description:
      "A complete studio lighting concept with three controllable lights, modifiers, stands, and a carry case for serious creators and small production teams.",
    specifications: {
      lights: "3 COB LED fixtures",
      output: "Up to 300 W each",
      control: "DMX, app, and onboard",
      kit: "Modifiers, stands, and case",
    },
    rating: 4.8,
    reviews: 2,
    warranty: "2 Year Seller Warranty",
    stock: 1,
    createdAt: "2026-07-29",
  },
  {
    id: 30,
    name: "LabelFlow Industrial Printer",
    brand: "Mila-Karton Business",
    image: "/images/img30.avif",
    category: "Printers",
    price: 149999,
    originalPrice: 169999,
    shortDescription:
      "Professional label printer for retail, warehouse, and small-business operations.",
    description:
      "A high-duty label printer concept for barcode, shipping, inventory, and product labelling workflows with network-ready operation.",
    specifications: {
      printType: "Thermal transfer",
      printSpeed: "Up to 8 ips",
      width: "4-inch labels",
      connectivity: "Ethernet, USB, Wi-Fi",
    },
    rating: 4.6,
    reviews: 3,
    warranty: "1 Year Manufacturer Warranty",
    stock: 2,
    createdAt: "2026-07-30",
  },
].map((product) => ({ ...common, ...product }));

export default demoproducts;
